### PR TITLE
Add basic telemetry implementation

### PR DESCRIPTION
**Pull request by Ch4s3**
This PR adds some telemetry events for query starts and stops.

### Implementation
- added telemetry dep
- added 4 events
- simple tests

## Future Work
- document events
- add more events
- unify logging around failures and heartbeats
- make logging options or only telemetry events

### CODE REVIEW

**Review by zbarnes757 — APPROVED** [review]
LGTM

**Comment by Ch4s3** [comment]
based on https://github.com/elixir-plug/plug/blob/c26c331395ce60e1945b6ee1d099ea11cd51cfd2/lib/plug/telemetry.ex

**Review by superhawk610 — APPROVED** [review]

**Review by pggalaviz — APPROVED** [review]
LGTM

**Review by dustinfarris — APPROVED** [review]
LGTM.  We will use this immediately.

Nice telemetry unit testing 👍

**Pull request merged**
