### PR TITLE
Misc doc changes

### PR DESCRIPTION
**Pull request by kianmeng**
Besides other documentation changes, this commit ensures the generated
HTML doc for HexDocs.pm will become the source of truth for this Elixir
library and leverage on latest features of ExDoc.

### CODE REVIEW

**Comment by kianmeng** [comment]
@Ch4s3 Should I resolve the conflict and resubmit the PR again?

**Comment by Ch4s3** [comment]
@kianmeng yes, please. We're trying to figure out how we want to take PR submissions so it's taken us a while to get back to you.

**Comment by kianmeng** [comment]
@Ch4s3 Done. Please check again.

**Comment by Ch4s3** [comment]
@kianmeng we have a large change upcoming in #32. That should be merged today, can you re-evaluate this update after those changes land?

**Comment by Ch4s3** [comment]
@kianmeng The update is in. We're testing it now, so there may be more changes soon.

**Review by Ch4s3 — APPROVED** [review]

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Pull request merged**
